{% set version = "1.7-5.2.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geor
  version: {{ version|replace("-", "_") }}

source:
  fn: geoR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/geoR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/geoR/geoR_{{ version }}.tar.gz
  sha256: 3895e49c005a5745738d190ccaad43bb0aa49c74465d4d0b4dd88c5850ed63b9
  patches:
    # https://github.com/rocker-org/rocker/issues/213#issuecomment-278909502
    - no_tcltk.patch

build:
  merge_build_host: True  # [win]
  number: 1
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mass
    - r-randomfields
    - r-sp
    - r-splancs
  run:
    - r-base
    - r-mass
    - r-randomfields
    - r-sp
    - r-splancs

test:
  commands:
    - $R -e "library('geoR')"  # [not win]
    - "\"%R%\" -e \"library('geoR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=geoR
  license: GPL (>= 2)
  summary: Geostatistical analysis including traditional, likelihood-based and Bayesian methods.

extra:
  recipe-maintainers:
    - ocefpaf
