{% set version = "1.8-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geor
  version: {{ version|replace("-", "_") }}

source:
  fn: geoR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/geoR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geoR/geoR_{{ version }}.tar.gz
  sha256: 990647804590b925a50f72897b24bbabd331cebef0be1696a60528b2f79d6fd3
  patches:
    # https://github.com/rocker-org/rocker/issues/213#issuecomment-278909502
    - no_tcltk.patch

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-randomfields
    - r-sp
    - r-splancs
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-randomfields
    - r-sp
    - r-splancs

test:
  commands:
    - $R -e "library('geoR')"           # [not win]
    - "\"%R%\" -e \"library('geoR')\""  # [win]

about:
  home: http://www.leg.ufpr.br/geoR
  license: GPL (>= 2)
  summary: Geostatistical analysis including traditional, likelihood-based and Bayesian methods.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
