appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: CGPz7CM5yx2vizbKZZxAsx0ZgATfZXCI988A1kCeaW/vRm6sniscCWstM+lzgCxVXmLcLPBddc/7xGPPT9NKaVwCHLGrkVHxT4zbzcH5c3s7Pr202hkch35x6B8BFOZ0vmfgW/gN9g46EameBWKsfqqgH5ecx5g9dl8c944dp8LwelqSyvB5CWpHpRxk9DuyBkCo0Fuzj8bK80jZXxuM5NiLmGQzk/exGVYjK8hFPIjRCU/z2J6MGBUOoLcnfp75S8eto2XbGjRmG7O0idClXya1sJTvNG1yzLAo9VRRZpfadqJibkEpDYiSDr6zPmytbrrrKu54qxJJsmTmvbcMFreZBcsYEawn9iZtnarPlU58U3wDzRzJzlTqEiKlZXiQDGpmNaLRmavIzoJ7z1pwQkor0Egb9HcmqFAUfrG2p2C/5f2vLE5r4POYE9+y0OJ8C/hOPB2yG0+f4/QlnKn0LYI7q9eaKQJgEzU2IPIkbbHg/TnTxuG39septpP3UB93SV5WFmY/HhgGbJqwjTn+tgJBibGaAr+GhvjCpgAirjLdxJ+qs5VOySOmDLpUwes1Gl2AQQ/mb+9cFr9mHrfZEO0WnMg+Llfe8/kGPRTnYOCa7s+HQNiU3tDv9yEeTzTz+L7+NC5EziNbG0quoqjwVudfck/hfVXL+afS61uaeP4=
conda_forge_output_validation: true
