travis:
  secure:
    BINSTAR_TOKEN: Y+0YL/ZFClFi5iXjoP5VoQl1H9RaJZu9ITNtJDaSp2v6Liz8sJXi0PzdgUZm/HJxgAKxupQRlpYZfzI9aLRCPS0/0zttSiWaFl6bclmEYJPZeqoLLiLGFlnByf+CSQdjRXvXnUU9vb8b3tl/XpdLXrl18j5fXHa17HhZuVPW9hJ59A9Pb7NZOVUaWKuC117yX0rh1vtZx/LdVKIMXHTeT6sGmxkpM0CPJqrWwP+xk78WFZhpbVGfEq9Fy9SahKCPPGtG+67FaTimNAFJ1rAobd8yl6dUr2NnuEM5yfvjhCLm3gZdP059NofGUk0YEBJiRAhc7+YlG29fxHUstqr3Pz3B3vrzpYn5hj+8T0SCN5GIgnJIeDjzK/xLZ7JTI4A+tHAMJyfx7akbxlYckxV20GIROUhoGu8GzxrR8phSvyTLPQPgFc+8/Ld0N4v/4Sf2gU1QLGYfR+KmmPXbPXW7piZJegdpCfFIVgwUZKtygMLzpJVIb9D3c4RTUxdThxBPX5OIHmtgI2Ds2MKdzHs5/GAfpWZkkN6NwYTzWkXiACpMHjMoQcLI0YZpG+4rxkG+s2z22vG2ssqvRUrod3cMND7KcAeG5tg6pJYeTDRmCbaE2Wc5aIHr637zZIYkCRvniXy/LZyUv2CpmTdtoopqGfi+kEbVIEA2f9R+rNe2Dv0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
